This space is used for modeling using keras

First, upload data

In [27]:
from google.colab import files
uploaded = files.upload()

Saving EURUSD15m1y41c.csv to EURUSD15m1y41c.csv


Read data in a pandas data frame

In [0]:
import io
import pandas as pd
import numpy as np
df = pd.read_csv(io.BytesIO(uploaded['EURUSD15m1y41c.csv']))

In [0]:
df = df.drop(columns=['Date'])

Split data and get the shape 

In [32]:
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets.samples_generator import make_blobs
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import GaussianNB
#df = df.to_numpy()
X = df[:,0:40]

scaler = MinMaxScaler()
a = scaler.fit(X)
X = scaler.transform(X)


#scale X
Y = df[:,41]
X_train, X_test, y_train, y_test = train_test_split(df, Y, test_size=0.2)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

(21562, 42) (21562,)
(5391, 42) (5391,)


Configure the model(Choose one)


*   tanh (hyperbolic tangent)
*   elu
*   softmax
*   selu
*   softplus
*   softsign
*   relu (Rectified linear units)
*   sigmoid (logistic)
*   hard_sigmoid
*   exponential 
*   linear 














In [0]:
import tensorflow as tf
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(42, input_dim=42, activation='relu'),
  tf.keras.layers.Dense(8, activation='relu'),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

**Compile the model (Choose one)**

*   mean_squared_error
*   mean_absolute_error
*   mean_absolute_percentage_error
*   mean_squared_logarithmic_error
*   square_hinge
*   hinge
*   categorical_hinge 
*   logcosh
*   huber_loss 
*   catergorical_crossentropy 
*   sparse_categorical_crossentropy
*   binary_crossentropy 
*   kullback_leibler_divergence 
*   poisson
*   cosine_proximity 
*   is_categorical_crossentropy 






















*   Binary Crossentropy


In [0]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['binary_accuracy'])

Train and evaluate the model

In [35]:
model.fit(X_train, y_train, epochs=100)
model.evaluate(X_test,  y_test, verbose=2)

Train on 21562 samples
Epoch 1/100
21562/21562 [==============================] - 1s 52us/sample - loss: 598.1305 - binary_accuracy: 0.4953
Epoch 2/100
21562/21562 [==============================] - 1s 50us/sample - loss: 206.1527 - binary_accuracy: 0.5019
Epoch 3/100
21562/21562 [==============================] - 1s 52us/sample - loss: 189.6782 - binary_accuracy: 0.4939
Epoch 4/100
21562/21562 [==============================] - 1s 50us/sample - loss: 134.9582 - binary_accuracy: 0.5014
Epoch 5/100
21562/21562 [==============================] - 1s 46us/sample - loss: 102.3409 - binary_accuracy: 0.5005
Epoch 6/100
21562/21562 [==============================] - 1s 46us/sample - loss: 79.0890 - binary_accuracy: 0.5003
Epoch 7/100
21562/21562 [==============================] - 1s 48us/sample - loss: 58.9006 - binary_accuracy: 0.4967
Epoch 8/100
21562/21562 [==============================] - 1s 48us/sample - loss: 54.8536 - binary_accuracy: 0.4974
Epoch 9/100
21562/21562 [===================

[0.6936450178272493, 0.49823782]

Test the model

In [36]:
y_pred = model.predict_classes(X_test)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

Evaluate model using the confusion matrix

In [37]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test.round(),y_pred.round())
print(cm)

[[2686    0]
 [2705    0]]


array([1., 1., 1., ..., 1., 0., 1.])